#!/bin/bash

# N.B. meteor is supported only in bundled form, which makes it equal to nodejs
if [ "$1" != "full" ] && [ "$1" != "ruby" ] && [ "$1" != "nodejs" ] && [ "$1" != "python" ] 
then
	echo "Usage: build <flavor> (where <flavor> = full, ruby, nodejs, python)"
	exit
else
	FLAVOR=$1
fi

VERSION=0.1
BUILDPATH=/imgbuild
OUTFILE=.$BUILDPATH/generated_main_installer.sh

function install() {
	echo "$BUILDPATH/$1" >> $OUTFILE
}

echo "#!/bin/bash" > $OUTFILE
echo "# (autogenerated by build.sh, edits will be lost)" >> $OUTFILE
chmod a+x $OUTFILE

install "install_my_init.sh"
install "install_nginx_passenger.sh"

if [ $FLAVOR == "full" ]
then
	install "install_rubyapp_utils.sh"
	install "install_nodejsapp_utils.sh"
	install "install_pythonapp_utils.sh"
else
	install "install_${FLAVOR}app_utils.sh"
fi

sudo docker build -t phusion/passenger-redhat-${FLAVOR}:${VERSION} .
